// Flappy Raccoon's art (port of src/kpapp/game/flappy/art.py). Generated by
// tools/generate_flappy_assets.py; all art is original and procedural. The
// manifest carries the gameplay numbers (hit radius, ground height) so they
// travel with the sprites.
//
// Nothing here touches the DOM until loadArt() is called, so game.js can import
// it under Node.

import { loadImage, loadJSON } from "../../core/gfx.js";

export const ASSET_URL = new URL("../../../assets/flappy/", import.meta.url);
export const MEDAL_NAMES = ["bronze", "silver", "gold", "platinum"];

let cache = null;
let pending = null;

/**
 * The loaded art, shaped like FlappyArt:
 *   birdFrames    images, identical size; wing up -> mid -> down
 *   birdHitRadius collision radius in px at native bird size
 *   pipeBody      PIPE_WIDTH wide, tiles vertically
 *   pipeCap       lip drawn at a pipe's open end (flip for top pipes)
 *   sky           1280x720 far background (sky gradient, sun/clouds)
 *   skyline       1280 wide, tiles horizontally; mid-layer scenery
 *   ground        1280 wide, tiles horizontally; height = groundHeight
 *   groundHeight
 *   feather       small white particle for flap bursts (tinted at load)
 *   medals        {bronze, silver, gold, platinum}
 *   panel         rounded scoreboard panel for game over
 */
export function cachedArt() {
  return cache;
}

export async function loadArt({ reload = false } = {}) {
  if (cache && !reload) return cache;
  if (pending && !reload) return pending;
  const url = (name) => new URL(name, ASSET_URL).href;
  pending = (async () => {
    let spec;
    try {
      spec = await loadJSON(url("manifest.json"));
    } catch (err) {
      throw new Error(`Flappy Raccoon art is missing (${err.message}). `
        + "Run: uv run python tools/generate_flappy_assets.py");
    }
    const img = (name) => loadImage(url(name)).catch(() => {
      throw new Error(`missing assets/flappy/${name}. Run: uv run python tools/generate_flappy_assets.py`);
    });
    const n = Number(spec.bird_frames);
    const [birdFrames, pipeBody, pipeCap, sky, skyline, ground, feather, panel, medalImgs] =
      await Promise.all([
        Promise.all(Array.from({ length: n }, (_, i) => img(`bird_${i}.png`))),
        img("pipe_body.png"), img("pipe_cap.png"), img("sky.png"), img("skyline.png"),
        img("ground.png"), img("feather.png"), img("panel.png"),
        Promise.all(MEDAL_NAMES.map((m) => img(`medal_${m}.png`))),
      ]);
    cache = {
      birdFrames,
      birdHitRadius: Number(spec.bird_hit_radius),
      pipeBody,
      pipeCap,
      sky,
      skyline,
      ground,
      groundHeight: Number(spec.ground_height),
      feather,
      medals: Object.fromEntries(MEDAL_NAMES.map((m, i) => [m, medalImgs[i]])),
      panel,
    };
    return cache;
  })();
  try {
    return await pending;
  } finally {
    pending = null;
  }
}
