"""Asset schema for Flappy Bird. Generated by tools/generate_flappy_assets.py.

All art is original and procedural. A manifest carries the gameplay-relevant
numbers (hitbox, ground height) so they travel with the art.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np

ASSET_DIR = Path(__file__).resolve().parents[4] / "assets" / "flappy" / "generated"
MANIFEST = ASSET_DIR / "manifest.json"


class AssetsMissingError(RuntimeError):
    pass


@dataclass
class FlappyArt:
    bird_frames: list[np.ndarray]  # BGRA, identical size; wing up -> mid -> down
    bird_hit_radius: int  # collision radius in px at native bird size
    pipe_body: np.ndarray  # BGRA, PIPE_WIDTH wide, tiles vertically
    pipe_cap: np.ndarray  # BGRA lip drawn at a pipe's open end (flip for top pipes)
    sky: np.ndarray  # BGR 1280x720 far background (sky gradient, sun/clouds)
    skyline: np.ndarray  # BGRA, 1280 wide, tiles horizontally; mid-layer scenery
    ground: np.ndarray  # BGR, 1280 wide, tiles horizontally; height = ground_height
    ground_height: int
    feather: np.ndarray  # BGRA small particle for flap bursts, tintable white
    medals: dict[str, np.ndarray]  # BGRA: "bronze", "silver", "gold", "platinum"
    panel: np.ndarray  # BGRA rounded scoreboard panel for game over


_cache: FlappyArt | None = None


def _read(name: str, flags: int = cv2.IMREAD_UNCHANGED) -> np.ndarray:
    path = ASSET_DIR / name
    if not path.exists():
        raise AssetsMissingError(
            f"missing {path.name}. Run: uv run python tools/generate_flappy_assets.py"
        )
    img = cv2.imread(str(path), flags)
    if img is None:
        raise AssetsMissingError(f"could not decode {path}")
    return img


def load_art(*, reload: bool = False) -> FlappyArt:
    global _cache
    if _cache is not None and not reload:
        return _cache
    if not MANIFEST.exists():
        raise AssetsMissingError(
            f"missing {MANIFEST}. Run: uv run python tools/generate_flappy_assets.py"
        )
    spec = json.loads(MANIFEST.read_text())
    _cache = FlappyArt(
        bird_frames=[_read(f"bird_{i}.png") for i in range(int(spec["bird_frames"]))],
        bird_hit_radius=int(spec["bird_hit_radius"]),
        pipe_body=_read("pipe_body.png"),
        pipe_cap=_read("pipe_cap.png"),
        sky=_read("sky.png", cv2.IMREAD_COLOR),
        skyline=_read("skyline.png"),
        ground=_read("ground.png", cv2.IMREAD_COLOR),
        ground_height=int(spec["ground_height"]),
        feather=_read("feather.png"),
        medals={m: _read(f"medal_{m}.png") for m in ("bronze", "silver", "gold", "platinum")},
        panel=_read("panel.png"),
    )
    return _cache
